// <auto-generated/>
using System.Reflection;

[assembly: AssemblyTitleAttribute("Plainion.AppFw.Shell")]
[assembly: AssemblyProductAttribute("Plainion.AppFw.Shell")]
[assembly: AssemblyDescriptionAttribute("Plainion.AppFw.Shell")]
[assembly: AssemblyCopyrightAttribute("Copyright @ 2017")]
[assembly: AssemblyVersionAttribute("1.3.2.0")]
[assembly: AssemblyFileVersionAttribute("1.3.2.0")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const System.String AssemblyTitle = "Plainion.AppFw.Shell";
        internal const System.String AssemblyProduct = "Plainion.AppFw.Shell";
        internal const System.String AssemblyDescription = "Plainion.AppFw.Shell";
        internal const System.String AssemblyCopyright = "Copyright @ 2017";
        internal const System.String AssemblyVersion = "1.3.2.0";
        internal const System.String AssemblyFileVersion = "1.3.2.0";
    }
}
